### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by fatuhoku** [evermeer/EVURLCache#16]

**Comment by evermeer** [comment]
When reading the requirements for Carthage at: https://github.com/Carthage/Carthage
I think it is already supported.
I have never tested this library with Carthage.
Could you let me know the outcome if you try using this with Carthage?

**Comment by fatuhoku** [comment]
Hmmm. I think not actually — there's a dependency on ReachabilitySwift that needs resolving. Will need to add a `Cartfile`

**Comment by evermeer** [comment]
I have never worked with Carthage, so it will take some time for me to find out what I should do to make this library compatible. If you know a quick fix for this, then a pull request would be really welcome 😀

**Comment by icecooly** [comment]
me too.
EVURLCache is not support Carthage 
Dependency "EVURLCache" has no shared framework schemes for any of the platforms: iOS

**Comment by evermeer** [comment]
Is now added
