### ISSUE TITLE
caching html file

### ISSUE THREAD

**Issue by amz4u2nv** [evermeer/EVURLCache#17]
Hi, I find the library very useful, but just have one issue.
It doesn't seem to be caching the .html file, is this possible, do I need to switch on a parameter, etc..
The file size of the html is 3.4Kb so its not big at all.
I can see it tries to check the precache folder for it, but once it doesnt find it, it just uses the live one.
If i disable internet it comes up blank.

Thanks

**Comment by evermeer** [comment]
If it can't find the file, then it's expected behavior that it will be downloaded or you will see a blank when there is no connection. So the question is why can't it find the file? Do you include the precache folder that includes the .html file in your build? If you set a breakpoint at line 85 and look at what the storagePath is. If you run the app on the simulator, then you should be able to open the folder that is mentioned in the storagePath and look what's there.

**Comment by amz4u2nv** [comment]
I don't have a precache folder setup, i would like a cache version of the html to be downloaded when I have internet - but I can't seem to see it where I see the other files - 
2016-04-14 14:56:35.981  CACHE not found in /Users/****/Library/Developer/CoreSimulator/Devices/A33D560D-49CB-498D-A15C-BA3B527F66CD/data/Containers/Bundle/Application/B0F6C69F-7A21-4FDB-9EBF-C9DEA935FF28/BBR.app/PreCache/www.***.com/get-app-homepage.html

I can see all images, css and js being cached - 
Returning cached data from /Users/xxx/Library/Developer/CoreSimulator/Devices/A33D560D-49CB-498D-A15C-BA3B527F66CD/data/Containers/Data/Application/6A89E28A-D8F7-471B-A0FC-D8C774FD1637/Documents/Cache/master.xxxx.com/css/app.css

Thanks for your quick replies.

**Comment by amz4u2nv** [comment]
Just to add I'm using the objective c files

**Comment by evermeer** [comment]
So it looks like the .html file is not saved to the Cache folder. During cashing a lot is written to the output log. Do you see any log message about the .html file? There should be a reason there why it's not cached. 

Is the HTTP status code OK?
https://github.com/evermeer/EVURLCache/blob/objective-c/pod/EVURLCache.m#L121

Could it be the cashing policy?
https://github.com/evermeer/EVURLCache/blob/objective-c/pod/EVURLCache.m#L131

Or is it just a write error?
https://github.com/evermeer/EVURLCache/blob/objective-c/pod/EVURLCache.m#L151

**Comment by amz4u2nv** [comment]
Thanks for your help.. it was caching policy, nocache for the html file.
I've a set the header expire for 2 days... but is it possible to ignore the caching policy on the file

My case would be - 
If connected to the internet
get the file from the internet,
if not connect to the internet then just use the local files that were cached either from precache folder or files that were downloaded when there was internet.

so this way it just ignores the caching policy of the files altogether..

Thanks for your help.

**Comment by evermeer** [comment]
Well, the easiest fix would be removing the cache policy check that you can find at the lines 125 to 135 in the EVURLCache class
https://github.com/evermeer/EVURLCache/blob/objective-c/pod/EVURLCache.m#L125

A better solution would be adding a static property to the EVURLCache which is default to true and only execute the cache check if the property is set to true. Then you could override the cache policy check.

**Comment by amz4u2nv** [comment]
Thanks that did the trick.
