### ISSUE TITLE
WKWebView support?

### ISSUE THREAD

**Issue by basememara** [evermeer/EVURLCache#20]
Hey, great plugin! Do you know if `WKWebView` is supported? For example, I'm loading an HTML string like this:
```
webView.loadHTMLString("<html><head><link href="styles.css" /><script src="script.js" /></head><body>...</body></html>", baseURL: NSURL(string: 'http://example.com'))
```
Does this mean those files can be in `/PreCache/example.com/` and it will pull them locally instead of the web?

**Comment by basememara** [comment]
I created a sample and looks like there's an issue with `WKWebView` #21

**Comment by evermeer** [comment]
Sorry, WKWebView does not use the Cocoa stack with NSProtocol, NSUrl, NSUrlCache. When using WKWebView there is no alternative to do anything similar. (as far as I know)

For more info see for instance:
http://stackoverflow.com/questions/29573840/wkwebview-and-nsurlcache-to-serve-local-content

If you do want to use EVURLCashe (which is based on the NSUrlCache) Then you need to use the UIWebview

**Comment by evermeer** [comment]
Closing this issue since WKWebView does not use NSUrlCache and therefore can never be supported by EVURLCache
