### ISSUE TITLE
Query params not taken into account when caching.

### ISSUE THREAD

**Issue by gregkerzhner** [evermeer/EVURLCache#23]
The current caching strategy does not take into account query params.  Therefore, a request like
```
https://snacks.com?search=stuff
```
and 
```
https://snacks.com?search=otherstuff
```
would be cached under the same file.  To fix this
```
request.URL?.query
```
should be included in the path of the cached file if it exists. 

PR: https://github.com/evermeer/EVURLCache/pull/22

**Comment by evermeer** [comment]
This is now pushed as version 2.7.0
