### ISSUE TITLE
Files placed in PreCache are not found

### ISSUE THREAD

**Issue by superoul** [evermeer/EVURLCache#28]
I've tried both in a custom application as well as running the example application right away.
Added another folder to the app without any luck as well.

Not sure if this is a EVURLCache problem rather than something else but writing and reading from the cache folder works. 

The top folder is named according to the domain name convention.
When I try in the simulator and later opens the PreCache folder, the files are there.
But the PreCache folder cannot be accessed.

**Comment by evermeer** [comment]
When you run the app and the files are not fetched from the PreCache folder, will they be downloaded and stored in the cache folder? If so, is the structure in the cache folder the same as you have in the PreCashe folder? You could force that by copying all your files from the cache folder to the PreCache folder.

Can you see in the log what exactly happens? You should have set: EVURLCache.LOGGING = true

When you run in the simulator you can get a precache path from the log and open that in the finder. Do you indeed see the PreCache files there? If not, have you included the PreCache folder in your target?

**Comment by superoul** [comment]
Hi!
Yes! I've logging enabled and everything looks as it should.
- Files not fetched from precache are downloaded and stored in the cache folder.
- I can see the files when I run in the simulator and open printed the PreCache path.
- When I debug this I turn off internet in so it's failing on the first file (index.html).

I added some code to list the contents of the precache directory if the file isn't found in the precache folder. The odd thing here is that that call tells me that the folder doesn't exists.
But at the same place in the code, I've added code to print the contents of NSBundle.mainBundle().resourcePath. And that clearly lists the PreCache folder.

I tried to run the example app directly though I suspected that I might have configured my xcode project incorrect. But I have the same issue there.

**Comment by evermeer** [comment]
That's strange... What X Code and iOS version are you testing on?

**Comment by superoul** [comment]
Xcode 7.3  Base Sdk 9.3

**Comment by superoul** [comment]
I see that there's an update available for xcode.
I will download it and try with the latest version.

**Comment by evermeer** [comment]
Is this still an issue?

**Comment by evermeer** [comment]
If you still have a problem with this, then just let me know...
