### ISSUE TITLE
Swift 3 version would be so nice !

### ISSUE THREAD

**Issue by nmDejamobile** [evermeer/EVURLCache#32]
As Swift 3 is out, a compatible version of EVURLCache would be nice.
For the moment I embed the lib in my project and convert it to Swift 3.

**Comment by evermeer** [comment]
Converting all my libraries to Swift 3 is on top of my todo list.
I'm currently struggling with one of my other libraries to convert it to Swift 3

**Comment by evermeer** [comment]
I just added a Swift 3 branch. I will merge this to master in about 1 or 2 weeks

**Comment by erawhctim** [comment]
Any update on the Swift 3 support? I see some work was done on the `Swift3` branch but can't tell if it was finished/merged or not

**Comment by evermeer** [comment]
@erawhctim It was merged to master on october 23. I will remove the Swift 3 branch so that there can be no confusion.
