### ISSUE TITLE
Cache eviction / current disk usage not implemented?

### ISSUE THREAD

**Issue by lightandshadow68** [evermeer/EVURLCache#40]
When caching response data, the currentDiskUsage property does not appear to update. Does cached content get evicted if the maximum disk size is exceeded?

**Comment by evermeer** [comment]
No, there is no mechanism for currentDiskUsage calculation or cleaning the cach if the maximum disk size is exceeded. EVURLCache is meant to be used as a mechanism for letting your app work even if there is no connection. Cleaning the cache would limit that functionality. 

There is a function for cleaning up expired cache items. You have to call that function manually.
