### ISSUE TITLE
Not logging anything.

### ISSUE THREAD

**Issue by tuhinsbuddy** [evermeer/EVURLCache#41]
Successfully integrated using pod. Using the version "2.10.0" in Swift 2.2 and Xcode 7.3.1 but not able to cache anything while hitting URL on UIWebView. Upon setting "EVURLCache.LOGGING = true" its not even logging anything on console. Please take a look and respond back. Following is the complete code inside "AppDelegate.swift".

                EVURLCache.LOGGING = true
                EVURLCache.MAX_FILE_SIZE = 26
                EVURLCache.MAX_CACHE_SIZE = 30
                EVURLCache.FORCE_LOWERCASE = true
                EVURLCache.activate()

BTW it is working when integrated in a blank and new project.

**Comment by evermeer** [comment]
Thanks for creating an issue here... I now remember that you also send an email a while back. An issue here will make me not forget it :-) 

Could you please try doing the .activate on the controller where you have the UIWebView? Maybe you have some other code in your project that is setting the NSURLCache? There can only be one active at a time.

**Comment by tuhinsbuddy** [comment]
Understood. Currently digging into that as per your suggestion. One more thing is that is there any way to remove the cache from EVURLCache as per the URL on the fly. Like on button click or from inside an IBAction..??

**Comment by tuhinsbuddy** [comment]
Closing the issue. As I found another NSUrlCache modification inside my project. BTW Thanks for the help.
