### ISSUE TITLE
Cache not working with Swift 3 - Optional wrap

### ISSUE THREAD

**Issue by BOSSoNe0013** [evermeer/EVURLCache#43]
Hi,
i notice that cache directory are not correctly created as localUrl is store in an optional string eg:
`
Cache/optional("host.domain.tld/index.html")_post_get_arguments
`
Perhaps you don't unwrap the localUrl string before concatenation with query and cache root ?

**Comment by evermeer** [comment]
Thanks for reporting this!
I have fixed this in version 3.2.1
