### ISSUE TITLE
PRECACHE not found

### ISSUE THREAD

**Issue by s2imon** [evermeer/EVURLCache#45]
Hi there Edwin, this isn't exactly an issue since I'm sure the problem lies with me somewhere. Reading through your existing answers I've seen that you've given friendly replies even to quite rough requests. Therefore I dare ask for your opinion. 

I'm trying to write a tutorial for how to cache a privacy policy locally, which your implementation seems to be perfectly suited for. I've recreated your structure for a PreCache folder in the root, then iubenda.com/privacy-policy folder and finally the 8051057 file in the folder (saved as html). 

EVURLCache.swift(123) cachedResponse(for:):
	PRECACHE not found /var/mobile/Containers/Data/Application/7C2EBF0D-5F1E-40B9-86E0-7DFFCF5240DE/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html

05/11/2017 22:37:15:088 App name)[9016:.] EVURLCache.swift(126) cachedResponse(for:):
	CACHE not found /var/containers/Bundle/Application/2F199D2F-8228-48CD-8896-EFDD321AC0C4/App name.app/PreCache/www.iubenda.com/privacy-policy/8051057/index.html

Where am I going wrong? Thanks a bunch :)

update: running it again an hour later it gives me: 

"CACHE not rewriting stored file" and returns a white page. I think that's is progress. I now only need to find the reason for it returning a white page both off- and online. Also I found almost an [identical posting here](https://github.com/evermeer/EVURLCache/issues/29) when googling for CACHE not rewriting stored file. Sorry about that.

**Comment by evermeer** [comment]
Hi, could you try deactivating the line:
`URLProtocol.registerClass(EVURLProtocol.self)`
In EVURLCashe and see if it's then working.
That line was there to react on http redirects, but it seems to give more problems than it solves.

Instead of creating a file in the PreCache folder, you could also just run the app and then copy over the file from the Cache folder to the PreCache folder. Then you know that the format and filename are correct.

**Comment by s2imon** [comment]
Thanks a bunch for the answer. I've gone down your recommended route and copied the Cache folders structure over into my app. Still the same output: web connection off - white UiWebView.

Connection on the content loads properly from the sites. This is the output when accessing the page in the privacy policy view. I'm puzzled and will step away from it for today:

`05/13/2017 22:15:14:119 appname)[10504:.] EVURLCache.swift(123) cachedResponse(for:):
	PRECACHE not found /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/assets/privacy_policy-7fc44af6a2afc58865325ce72b169021.css

05/13/2017 22:15:14:121 appname)[10504:.] EVURLCache.swift(126) cachedResponse(for:):
	CACHE not found /var/containers/Bundle/Application/37FA8E9D-7AAE-4253-9889-37C0ADEDC930/appname.app/PreCache/www.iubenda.com/assets/privacy_policy-7fc44af6a2afc58865325ce72b169021.css

05/13/2017 22:15:14:123 appname)[10504:.] EVURLCache.swift(123) cachedResponse(for:):
	PRECACHE not found /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/assets/privacy_policy-8d4bd4976bc7da7aa31d07fab367b627.js

05/13/2017 22:15:14:126 appname)[10504:.] EVURLCache.swift(169) cachedResponse(for:):
	The file is probably not put in the local path using NSKeyedArchiver /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/assets/privacy_policy-8d4bd4976bc7da7aa31d07fab367b627.js

05/13/2017 22:15:14:126 appname)[10504:.] EVURLCache.swift(241) storeCachedResponse(_:for:):
	Writing data to /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html

05/13/2017 22:15:14:149 appname)[10504:.] EVURLCache.swift(245) storeCachedResponse(_:for:):
	CACHE save file to Cache  : /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html

05/13/2017 22:15:14:155 appname)[10504:.] EVURLCache.swift(241) storeCachedResponse(_:for:):
	Writing data to /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/assets/privacy_policy-7fc44af6a2afc58865325ce72b169021.css

05/13/2017 22:15:14:164 appname)[10504:.] EVURLCache.swift(245) storeCachedResponse(_:for:):
	CACHE save file to Cache  : /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/assets/privacy_policy-7fc44af6a2afc58865325ce72b169021.css

05/13/2017 22:15:14:205 appname)[10504:.] EVURLCache.swift(241) storeCachedResponse(_:for:):
	Writing data to /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/assets/privacy_policy-8d4bd4976bc7da7aa31d07fab367b627.js

05/13/2017 22:15:14:212 appname)[10504:.] EVURLCache.swift(245) storeCachedResponse(_:for:):
	CACHE save file to Cache  : /var/mobile/Containers/Data/Application/xxx/Documents/Cache/www.iubenda.com/assets/privacy_policy-8d4bd4976bc7da7aa31d07fab367b627.js`

**Comment by evermeer** [comment]
In the demo app I tried this with url https://www.iubenda.com/privacy-policy/8051057
With internet connection I see the page.
If is turn off the internet and restart the app I have a blank page like you said.
I do see this in the output:

```
05/14/2017 16:35:20:740 EVURLCache)[71715:.] EVURLCache.swift(143) cachedResponse(for:):
	Returning cached data from /Users/eve21962/Library/Developer/CoreSimulator/Devices/6F1B814A-06B2-4720-A95A-A98050F8D056/data/Containers/Data/Application/1990D984-2A13-47B5-970A-75DC98F5F16B/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html

05/14/2017 16:35:20:767 EVURLCache)[71715:.] EVURLCache.swift(143) cachedResponse(for:):
	Returning cached data from /Users/eve21962/Library/Developer/CoreSimulator/Devices/6F1B814A-06B2-4720-A95A-A98050F8D056/data/Containers/Data/Application/1990D984-2A13-47B5-970A-75DC98F5F16B/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html

05/14/2017 16:35:20:770 EVURLCache)[71715:.] EVURLCache.swift(143) cachedResponse(for:):
	Returning cached data from /Users/eve21962/Library/Developer/CoreSimulator/Devices/6F1B814A-06B2-4720-A95A-A98050F8D056/data/Containers/Data/Application/1990D984-2A13-47B5-970A-75DC98F5F16B/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html

05/14/2017 16:35:20:773 EVURLCache)[71715:.] EVURLCache.swift(235) storeCachedResponse(_:for:):
	CACHE not rewriting stored file

05/14/2017 16:35:20:808 EVURLCache)[71715:.] EVURLCache.swift(143) cachedResponse(for:):
	Returning cached data from /Users/eve21962/Library/Developer/CoreSimulator/Devices/6F1B814A-06B2-4720-A95A-A98050F8D056/data/Containers/Data/Application/1990D984-2A13-47B5-970A-75DC98F5F16B/Documents/Cache/www.iubenda.com/assets/privacy_policy-7fc44af6a2afc58865325ce72b169021.css

05/14/2017 16:35:20:815 EVURLCache)[71715:.] EVURLCache.swift(143) cachedResponse(for:):
	Returning cached data from /Users/eve21962/Library/Developer/CoreSimulator/Devices/6F1B814A-06B2-4720-A95A-A98050F8D056/data/Containers/Data/Application/1990D984-2A13-47B5-970A-75DC98F5F16B/Documents/Cache/www.iubenda.com/assets/privacy_policy-8d4bd4976bc7da7aa31d07fab367b627.js

05/14/2017 16:35:20:818 EVURLCache)[71715:.] EVURLCache.swift(143) cachedResponse(for:):
	Returning cached data from /Users/eve21962/Library/Developer/CoreSimulator/Devices/6F1B814A-06B2-4720-A95A-A98050F8D056/data/Containers/Data/Application/1990D984-2A13-47B5-970A-75DC98F5F16B/Documents/Cache/www.iubenda.com/assets/privacy_policy-8d4bd4976bc7da7aa31d07fab367b627.js

05/14/2017 16:35:20:818 EVURLCache)[71715:.] EVURLCache.swift(143) cachedResponse(for:):
	Returning cached data from /Users/eve21962/Library/Developer/CoreSimulator/Devices/6F1B814A-06B2-4720-A95A-A98050F8D056/data/Containers/Data/Application/1990D984-2A13-47B5-970A-75DC98F5F16B/Documents/Cache/www.iubenda.com/assets/privacy_policy-7fc44af6a2afc58865325ce72b169021.css

05/14/2017 16:35:20:821 EVURLCache)[71715:.] EVURLCache.swift(235) storeCachedResponse(_:for:):
	CACHE not rewriting stored file

05/14/2017 16:35:20:822 EVURLCache)[71715:.] EVURLCache.swift(235) storeCachedResponse(_:for:):
	CACHE not rewriting stored file
```

But when I use the safari developer option to inspect the simulator, I see the following html:

```
<html id="iubenda_policy" class="iubenda_fixed_policy"><head>

  <title>Privacy Policy of Simon's app</title>
	
	<meta content="This Application collects some Personal Data from its Users." name="description">
	<meta content="privacy policy" name="keywords">

  <meta http-equiv="Content-Language" content="en">
  <meta name="robots" content="noindex, follow">

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta http-equiv="date" content="2017-02-24">
	<meta http-equiv="last-modified" content="2017-05-13">
	<meta property="og:title" content="Privacy Policy of Simon's app">
	<meta property="og:type" content="website">
	<meta property="og:image" content="https://www.iubenda.com/images/site/fb-image.png">
	<meta property="og:site_name" content="iubenda">
	<meta property="fb:app_id" content="190131204371223">
	<link rel="image_src" href="https://www.iubenda.com/images/site/fb-image.png">

  <meta name="viewport" content="width=device-width">

  <link href="/assets/privacy_policy-7fc44af6a2afc58865325ce72b169021.css" media="screen" rel="stylesheet" type="text/css">
  <script src="/assets/privacy_policy-8d4bd4976bc7da7aa31d07fab367b627.js" type="text/javascript"></script></head></html>
```

So the question is why the script does not render the page when offline

**Comment by evermeer** [comment]
Ah, and as I suggested, when I disable the line:

`URLProtocol.registerClass(EVURLProtocol.self)`

It works as it should. You will just see the page.
I just pushed that as a change to GitHub. If you just download EVURLCache and run the demo, then it should just work (first run it online, then offline)

**Comment by s2imon** [comment]
You're great, thanks for the support. I've redownloaded your repository, imported my folders, added my link. First running offline returns the screen in blank, just as on my main app. Running it online it shows the site. I've noticed an error on both my app and your demo app saying it has no sandbox access. It therefore is probably related to that.
I've done some initial googling, but haven't found any conclusive answers yet.

```
2017-05-15 10:59:36.785332+0200 EVURLCache[12173:abc] Cache is now active
2017-05-15 10:59:36.897876+0200 EVURLCache[12173:abc] navigating to https://www.iubenda.com/privacy-policy/8051057
2017-05-15 10:59:36.953494+0200 EVURLCache[12173:abcd] libMobileGestalt MobileGestaltSupport.m:153: pid 12173 (EVURLCache) does not have sandbox access for xyz and IS NOT appropriately entitled
2017-05-15 10:59:36.953553+0200 EVURLCache[12173:abcde] libMobileGestalt MobileGestalt.c:550: no access to InverseDeviceID (see <rdar://problem/11744455>)
05/15/2017 10:59:37:409 EVURLCache)[12173:.] EVURLCache.swift(125) cachedResponse(for:):
	PRECACHE not found /var/mobile/Containers/Data/Application/efg/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html
```

```
05/15/2017 10:59:37:413 EVURLCache)[12173:.] EVURLCache.swift(171) cachedResponse(for:):
	The file is probably not put in the local path using NSKeyedArchiver /var/mobile/Containers/Data/Application/efg/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html

05/15/2017 10:
```
```59:37:433 EVURLCache)[12173:.] EVURLCache.swift(125) cachedResponse(for:):
	PRECACHE not found /var/mobile/Containers/Data/Application/efg/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html
```

```
05/15/2017 10:59:37:434 EVURLCache)[12173:.] EVURLCache.swift(171) cachedResponse(for:):
	The file is probably not put in the local path using NSKeyedArchiver /var/mobile/Containers/Data/Application/efg/Documents/Cache/www.iubenda.com/privacy-policy/8051057/index.html
```

I'll get there!

**Comment by s2imon** [comment]
Hey there Edwin, I'm back into this issue. I cannot reproduce the issue I've had before 'MobileGestaltSupport.m:153: pid 12173 (EVURLCache) does not have sandbox access', however I have some more relevant questions. 

I've reproduced the demo app faithfully (except for some differences in the web view). Basically I'm getting the same PRECACHE not found problem. Then running your demo app I seem to hit against the same error, getting a blank page unless browsing with an internet connection. 

```
2017-06-15 08:17:01.929696+0200 EVURLCache[10203:5830680] Cache is now active
2017-06-15 08:17:02.060420+0200 EVURLCache[10203:5830680] navigating to https://evict.nl
06/15/2017 08:17:02:468 EVURLCache)[10203:.] EVURLCache.swift(125) cachedResponse(for:):
	PRECACHE not found /Users/name/Library/Developer/CoreSimulator/Devices/XYZ/data/Containers/Data/Application/ABC/Documents/Cache/evict.nl/index.html

06/15/2017 08:17:02:476 EVURLCache)[10203:.] EVURLCache.swift(171) cachedResponse(for:):
	The file is probably not put in the local path using NSKeyedArchiver /Users/name/Library/Developer/CoreSimulator/Devices/XYZ/data/Containers/Data/Application/ABC/Documents/Cache/evict.nl/index.html

06/15/2017 08:17:02:507 EVURLCache)[10203:.] EVURLCache.swift(125) cachedResponse(for:):
	PRECACHE not found /Users/name/Library/Developer/CoreSimulator/Devices/XYZ/data/Containers/Data/Application/ABC/Documents/Cache/evict.nl/index.html

06/15/2017 08:17:02:508 EVURLCache)[10203:.] EVURLCache.swift(171) cachedResponse(for:):
	The file is probably not put in the local path using NSKeyedArchiver /Users/name/Library/Developer/CoreSimulator/Devices/XYZ/data/Containers/Data/Application/ABC/Documents/Cache/evict.nl/index.html

2017-06-15 08:17:02.517590+0200 EVURLCache[10203:5830768] TIC TCP Conn Failed [1:0x600000171100]: 1:50 Err(50)
2017-06-15 08:17:02.518494+0200 EVURLCache[10203:5830768] HTTP load failed (error code: -1009 [1:50]) for Task <A376062A-1072-4160-90FB-09A164947AFD>.<0>
2017-06-15 08:17:02.518836+0200 EVURLCache[10203:5830767] NSURLConnection finished with error - code -1009
```

My question: why does it seem to be looking for the PRECACHE under the Cache directory? 

Thank you!

**Comment by evermeer** [comment]
@s2imon It looks like the log messages are switched. This is in the code:

```
        // Check if there is a cache for this request
        let storagePath = EVURLCache.storagePathForRequest(request, rootPath: EVURLCache._cacheDirectory) ?? ""
        if !FileManager.default.fileExists(atPath: storagePath) {
            EVURLCache.debugLog("PRECACHE not found \(storagePath)")
            let storagePath = EVURLCache.storagePathForRequest(request, rootPath: EVURLCache._preCacheDirectory) ?? ""
            if !FileManager.default.fileExists(atPath: storagePath) {
                EVURLCache.debugLog("CACHE not found \(storagePath)")
                return nil
            }
        }
```
Do you see it first checks the cache and then reports the precache is not there. 
After that it checks the precache and reports that the cache is not there. 
The code order is correct. Its the log message that is wrong. 
I will push a fix for that now.

**Comment by s2imon** [comment]
Man and I thought I was getting closer. I'll try again soon, hopefully.
