### ISSUE TITLE
Uses cache on specific content, while others don't use cache at all?

### ISSUE THREAD

**Issue by babyghost666** [evermeer/EVURLCache#50]
I'm trying EVURLCache. Great stuff. However, is that possible that I write filter that uses cache, while others do not use cache at all? I know I can do that in reverse (filtering content not to use cache) now with the code below. How about I only want to cache some web view contents but not others?

![dpes4c0uqaanwhi](https://user-images.githubusercontent.com/5141074/33308389-387ee0aa-d455-11e7-901e-6cf063825681.jpg)

**Comment by evermeer** [comment]
I think you could just invert the filter so that it returns false by default and only true for your specific requests.

**Comment by babyghost666** [comment]
Thanks for the quick reply. I tried to disable the cache globally (like you said, returns false) it seems okay. But I found no way to add the specific URL in the cache again later in other view controllers. It may be due to the URL is redirected...I think ?

**Comment by evermeer** [comment]
With redirects, the redirect itself will never be cached. It's the response from where it was redirected to that will be cached. So that's also where you need to return true for in the filter.
