### ISSUE TITLE
How to store multiple URL in cache?

### ISSUE THREAD

**Issue by Sagar021** [evermeer/EVURLCache#53]
First Thank you for providing this library.
I am trying to store multiple web pages in the app I tried but it replacing with old URL. can you please suggest me how I store multiple pages in the cache.

**Comment by evermeer** [comment]
I'm not sure what you mean with that. EVURLCache is a caching mechanism that replaces the default cache. It is automatically handled for any URLRequest that you make. Even UIWebviews use URLRequest. Just open the demo app and navigate. You can see the number of files in the cache folder increasing. Multiple domains will be there.

**Comment by Sagar021** [comment]
Thanks for your rply..
i have multiple pages in same domain just changing parametrs like
www.google.com/page1
www.google.com/page2 etc
EVURLCache only store last requsted web page.
