### ISSUE TITLE
Is it available for android?

### ISSUE THREAD

**Issue by pankaj-bhalala** [evermeer/EVURLCache#54]
Hello,
I use this for iPhone and very very thank you for this beacause i didn't found another so it's very helpfull for offline webpage store.

 but i want it for android also,

If you or any one have this same offline webpage cache feature available in android than provide me.
Or URL post here.

**Comment by evermeer** [comment]
Sorry, I only do iOS. 

After a quick look I found this:
https://github.com/candrews/HttpResponseCache
You could use that mechanism and customize it so that it works like EVURLCache.
