### ISSUE TITLE
Some of the problems

### ISSUE THREAD

**Issue by xhzengAIB** [evermeer/EVURLCache#6]
Hi！@evermeer 

If I use 
AVPlayerItem * item = [AVPlayerItem playerItemWithURL: [NSURL URLWithString: @ "https://..."]]. Methods play video, 

can cache the video like this?

**Comment by evermeer** [comment]
I think (but I'm not sure) that AVPlayerItem will use the NSURLCache and therefore you should be able to use EVURLCache with it. You do have to set the cache size to be much larger than the file that you want to play.

**Comment by xhzengAIB** [comment]
Thank you very much for your reply
