### ISSUE TITLE
Google Places Autocomplete not working

### ISSUE THREAD

**Issue by schmidt9** [evermeer/EVURLCache#65]
Google Places SDK ver. 3.3.0(4.5) autocomplete is not working when using EVURLCache. Requests are being written to cache, and autocomplete seems not to like it, in simply doesn't return any search results. Looking for options to disable caching for Google Places.

**Comment by evermeer** [comment]
You can create your own filtering to prevent using the cache for specific files. You could do something like this:
        
```
       EVURLCache.filter { request in
            if request.url?.host == "places.google.com" {
                return false
            }
            return true
        }
```

**Comment by schmidt9** [comment]
Sorry I didn't point it, I use Obj C branch, can we do the same using Obj C?

**Comment by evermeer** [comment]
Ah, the filter functionality was added after the migration to swift. 
But it would be easy for you to add something like that In the EVURLCache.m file yourself. Just use the request object in the storeCachedResponse function and return if you don't want to cache
See https://github.com/evermeer/EVURLCache/blob/objective-c/pod/EVURLCache.m#L116

**Comment by schmidt9** [comment]
Ok so we should add some exclusion list for this to work

**Comment by schmidt9** [comment]
Say a static array of urls

**Comment by evermeer** [comment]
Yes, that would probably work.

**Comment by schmidt9** [comment]
Is it worth to make a Pull Request after that?

**Comment by evermeer** [comment]
Yes, if the code is generic. So you created the list outside EVURLCache.m and only have the logic for the inside it, then a pull request would we welcome.

**Comment by evermeer** [comment]
PR #66 is now merged
