### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aetsyss** [evermeer/EVURLCache#7]
hi
the app crashes trying to loadRequest from https://www.sbk.org

**Comment by evermeer** [comment]
Does the app also crash when you don't call [EVURLCache activate];
At what point does it crash?
What is the error message?

**Comment by evermeer** [comment]
EVURLCache is now converted to Swift 2
A demo app is added.
Just change the url to https://www.sbk.org on line 19 of ViewController.swift to see this in action

**Comment by aetsyss** [comment]
thanks!
